### ISSUE TITLE
找不到类 , 项目无法启动

### ISSUE THREAD

**Issue by xiaoCong2014** [dyc87112/swagger-starter-demo#2]
com.didispace.demo.DemoApplication 报错 , 找不到 com.didispace.swagger.EnableSwagger2Doc , pom.xml 依赖里确实没有相关的依赖

**Comment by wangys521yy** [comment]
确实找不到，这个包的路径变了，变成了com.spring4all.swagger.EnableSwagger2Doc。

**Comment by dyc87112** [comment]
@xiaoCong2014 感谢 @wangys521yy 已经提交了PR解决该问题

**Comment by dyc87112** [comment]
该starter贡献给了spring4all社区,所以groupid做了变更
